/**
 * P1-17 契约探针的 Plugin Pack fixture 工厂（tests/dsh-contract 专用）。
 *
 * 在 tmp 里复刻 Node preflight 的安装产物布局（apps/node/src/plugin/
 * runtime-config.ts `ensurePackOverlay` 的最小镜像），并渲染 Runtime 消费的
 * Cordis overlay yml：
 *
 * - 行形状与 apps/node/src/plugin/runtime-config.ts `renderPackOverlayYaml`
 *   互为镜像（`insert: [{ id, name, config }]`，id=cordisEntryId(name)、
 *   name=绝对路径 specifier、config={}；probe 用手写渲染替代 `yaml` 依赖，
 *   单行路径用单引号包裹——与本文件注释互引，勿在此引入生产实现）。
 * - specifier 用绝对路径直指 `<packsRoot>/<packDigest>/node_modules/<name>/
 *   <entrypoint>`：mountRootInclude 对 isAbsolute(name) 显式 pathToFileURL
 *   直连 import（dsh-app-boot 0.1.0-rc.8），与 baseUrl/bare 锚解耦——relative
 *   specifier 从 runtime-dsh config/ 解析、bare 名走 DSH 宿主锚目录，两条路
 *   都到不了本机 pack 目录（同 runtime-config.ts 模块解析策略注释）。
 * - peer 依赖锚：fixture 的 `@deepseek-ai/dsh-tools` 由 `<packDir>/node_modules/
 *   @deepseek-ai/dsh-tools` symlink 提供（pnpm 离线装包的 pack 树同形），目标
 *   是本包 node_modules 解析出的真实 dsh-tools 目录——与 Runtime 同一实例。
 * - pack.json marker 与 content store symlink（Node 侧契约）不在 probe 布局
 *   内：Runtime 只消费 overlay 行与 specifier，那两层由 apps/node 测试看管。
 * - 服务需求走插件自声明：cordis 对 ctx.* 服务访问按 fiber.inject 把门，
 *   fixture 源码自带 `export const inject = ['tools']`（生态契约——宿主原样
 *   挂载，不代替插件标注）。探针实证：无 inject 声明时 apply 内 ctx.tools
 *   访问抛 "cannot get property … without inject"。catalog review 负责挡住
 *   未声明 inject 的 ctx.* 插件（见 plugins/fixtures README）。
 *
 * 本目录属 Q3 契约探针，不进生产 bundle；绝对路径只存在于 tmp 与本地 wire
 * （红线同 runtime-wire 的 workspacePath，不进 Hub/日志/evidence）。
 */
import { cpSync, existsSync, mkdirSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gunzipSync } from 'node:zlib'
import { cordisEntryId, pluginCordisEntry, type PluginManifest } from '@whalepod/protocol'
import {
  compareCodePoints,
  digestPluginCordisEntry,
  digestPluginPack,
} from '@whalepod/protocol/plugin-pack-digest'

const REPO_ROOT = fileURLToPath(new URL('../../../../../', import.meta.url))
const FIXTURE_PACKAGE_DIR = join(REPO_ROOT, 'plugins/fixtures/whalepod-fixed-time')
const CATALOG_PATH = join(REPO_ROOT, 'plugins/catalog/whalepod-fixed-time.json')
const TARBALL_PATH = join(REPO_ROOT, 'plugins/tarballs/whalepod-fixed-time-0.1.0.tgz')

/** catalog 登记的 fixture 清单（PluginManifest 形状，apps/node 同一校验面）。 */
export function catalogManifest(): PluginManifest {
  return JSON.parse(readFileSync(CATALOG_PATH, 'utf8')) as PluginManifest
}

/** committed tarball（plugins/tarballs）绝对路径。 */
export function committedTarballPath(): string {
  return TARBALL_PATH
}

/** 与 apps/node/src/plugin/runtime-config.ts `PACK_OVERLAY_FILENAME` 一致的文件名。 */
const PACK_OVERLAY_FILENAME = 'cordis.overlay.yml'

export interface InstalledFixturePack {
  /** digestPluginPack（catalog manifest 派生）——Node/Runtimes 共同锚定的 pack 身份。 */
  readonly packDigest: string
  /** overlay yml 绝对路径（喂给 RuntimeSpec.pluginPackOverlayPath）。 */
  readonly overlayPath: string
  /** 渲染出的 overlay 文本（调试/断言用）。 */
  readonly overlayYaml: string
  /** pack 安装目录（= packsRoot/packDigest，runtime 加载的树就在其 node_modules 下）。 */
  readonly packDir: string
  readonly manifest: PluginManifest
}

interface OverlayRow {
  readonly id: string
  readonly name: string
  readonly config: Record<string, unknown>
}

/**
 * 手写 overlay 渲染：行形状与 apps/node/src/plugin/runtime-config.ts
 * `renderPackOverlayYaml` 互为镜像（rows 按 name 排序、lineWidth 不折叠——
 * 探针只有单行，用显式单引号保证路径永不折叠/无需转义）。
 */
function renderPackOverlayYaml(rows: readonly OverlayRow[], packDigest: string): string {
  // 排序与 apps/node renderPackOverlayYaml 同用 protocol 的码点比较器（镜像语义）。
  const sorted = [...rows].sort((a, b) => compareCodePoints(a.name, b.name))
  const header =
    '# whalepod plugin pack overlay — generated by the runtime-dsh contract probe (P1-17); do not edit.\n' +
    `# pack: ${packDigest}\n`
  const body = sorted
    .map((row) => `- insert:\n    - id: ${row.id}\n      name: '${row.name}'\n      config: {}\n`)
    .join('')
  return header + body
}

function writeOverlay(packDir: string, rows: readonly OverlayRow[], packDigest: string): string {
  const overlayPath = join(packDir, PACK_OVERLAY_FILENAME)
  writeFileSync(overlayPath, renderPackOverlayYaml(rows, packDigest), 'utf8')
  return overlayPath
}

/**
 * 把 catalog 登记的 fixture 插件装进 tmp 的 pack 布局并生成 overlay。
 * packDigest 用 Node 同一算法（digestPluginPack ∘ pluginCordisEntry）从 catalog
 * manifest 现算——Runtime spec.pluginPackDigest 与 overlay `# pack:` 头一致。
 */
export function installFixturePack(packsRoot: string): InstalledFixturePack {
  const manifest = catalogManifest()
  const configDigest = digestPluginCordisEntry(pluginCordisEntry(manifest))
  const packDigest = digestPluginPack({
    schemaVersion: 1,
    packages: [
      {
        name: manifest.name,
        version: manifest.version,
        integrity: manifest.integrity,
        dependencyLockDigest: manifest.dependencyLockDigest,
        entrypoint: manifest.entrypoint,
        configDigest,
      },
    ],
  })
  const packDir = join(packsRoot, packDigest)
  const packageDir = join(packDir, 'node_modules', manifest.name)
  mkdirSync(packDir, { recursive: true })
  // 安装树 = tarball 解包内容（apps/node 已验 tarball 字节 == fixture 源）。
  cpSync(FIXTURE_PACKAGE_DIR, packageDir, { recursive: true })
  anchorPeerDependency(packDir)
  const overlayPath = writeOverlay(
    packDir,
    [
      {
        id: cordisEntryId(manifest.name),
        // 与 ensurePackOverlay 同形：node_modules 锚 + entrypoint 的绝对路径。
        name: join(packageDir, manifest.entrypoint),
        config: {},
      },
    ],
    packDigest,
  )
  return {
    packDigest,
    overlayPath,
    overlayYaml: readFileSync(overlayPath, 'utf8'),
    packDir,
    manifest,
  }
}

/** `<packDir>/node_modules/@deepseek-ai/dsh-tools` → 本包真实 dsh-tools 目录。 */
function anchorPeerDependency(packDir: string): void {
  const require = createRequire(import.meta.url)
  const dshToolsDir = dirname(require.resolve('@deepseek-ai/dsh-tools/package.json'))
  const anchor = join(packDir, 'node_modules', '@deepseek-ai', 'dsh-tools')
  if (existsSync(anchor)) return
  mkdirSync(dirname(anchor), { recursive: true })
  symlinkSync(dshToolsDir, anchor, 'dir')
}

export interface InstalledCrashPluginPack {
  /** 崩溃插件的 overlay yml 绝对路径。 */
  readonly overlayPath: string
  /** 插件 id（= 包名；错误归因断言用）。 */
  readonly pluginId: string
  /** apply() 里脚本化的报错文本（断言错误可归因到插件自身）。 */
  readonly scriptedMessage: string
}

/**
 * 另造一个 apply() 即抛错的崩溃插件 overlay（02 Task 17 Step 8「插件崩溃不
 * 影响 Hub」的 Runtime 侧一半）：模块本身可 import（加载成功），激活阶段抛错
 * —— loader 记 fiber FAILED，boot 的 assertEntriesActivated 汇聚后 fail-closed。
 */
export function installCrashPluginPack(packsRoot: string): InstalledCrashPluginPack {
  const pluginId = 'whalepod-crash-plugin'
  const scriptedMessage = 'crash probe: apply() exploded on purpose (P1-17 isolation)'
  const packDir = join(packsRoot, 'crash')
  const packageDir = join(packDir, 'node_modules', pluginId)
  mkdirSync(packageDir, { recursive: true })
  writeFileSync(
    join(packageDir, 'package.json'),
    `${JSON.stringify({ name: pluginId, version: '0.1.0', type: 'module', main: 'index.js' })}\n`,
    'utf8',
  )
  writeFileSync(
    join(packageDir, 'index.js'),
    `export function apply() {\n  throw new Error(${JSON.stringify(scriptedMessage)})\n}\n`,
    'utf8',
  )
  const overlayPath = writeOverlay(
    packDir,
    [{ id: pluginId, name: join(packageDir, 'index.js'), config: {} }],
    'crash-probe-no-pack-digest',
  )
  return { overlayPath, pluginId, scriptedMessage }
}

export interface InstalledTamperedPack {
  /** 篡改后的 overlay yml 绝对路径（喂给 RuntimeSpec.pluginPackOverlayPath）。 */
  readonly overlayPath: string
  /** 渲染出的 overlay 文本（调试/断言用）。 */
  readonly overlayYaml: string
  /** 非法行指向的 id（错误归因断言用）。 */
  readonly offendingId: string
}

/**
 * 手写整份 overlay 文本（负例探针专用：行形状故意非契约，不走上面的
 * insert-only 渲染器；头注释明 adversarial，避免被误当成 preflight 产物）。
 */
function writeRawOverlayYaml(packDir: string, yaml: string, packDigest: string): string {
  const overlayPath = join(packDir, PACK_OVERLAY_FILENAME)
  const header =
    '# whalepod plugin pack overlay — ADVERSARIAL contract probe (P1-17 review M11); do not edit.\n' +
    `# pack: ${packDigest}\n`
  writeFileSync(overlayPath, header + yaml, 'utf8')
  return overlayPath
}

/**
 * 造一个被篡改的 pack overlay（P1-17 review M11 负例一）：合法 insert 行之外
 * 追加一行 id 定位 patch（`- id: <coreId>` + `disabled: true`）。vendor
 * applyEntryPatches 的 per-key 覆盖语义下（0.1.0-rc.8 已核实，后层胜），栈尾
 * 的这行会改写 dsh-base 核心条目；bridge 的行契约校验必须在入栈前拒绝。
 * offendingId 锚 dsh-base cordis.patch.yml insert 的核心条目 id（dsh 升级若
 * 改名，本探针的红灯提示同步）。
 */
export function installCoreOverridePack(packsRoot: string): InstalledTamperedPack {
  const offendingId = 'llm'
  const packDir = join(packsRoot, 'core-override')
  mkdirSync(packDir, { recursive: true })
  const overlayPath = writeRawOverlayYaml(
    packDir,
    // 第一行是契约内 insert 行：拒绝必须归因到第二行，而非「任何 overlay」。
    "- insert:\n    - id: whalepod-benign-row\n      name: '/absent/benign.js'\n      config: {}\n" +
      `- id: ${offendingId}\n  disabled: true\n`,
    'tampered-core-override-no-pack-digest',
  )
  return { overlayPath, overlayYaml: readFileSync(overlayPath, 'utf8'), offendingId }
}

/**
 * 造一个 insert id 与核心 id 冲突的 pack overlay（P1-17 review M11 负例二）：
 * insert 行的 id 取 dsh-base 核心层 insert 的条目 id——vendor 对同 id insert
 * 不去重（两条都会挂载），bridge 的 id 空间校验必须在入栈前拒绝。
 */
export function installIdCollisionPack(packsRoot: string): InstalledTamperedPack {
  const offendingId = 'llm'
  const packDir = join(packsRoot, 'id-collision')
  mkdirSync(packDir, { recursive: true })
  const overlayPath = writeRawOverlayYaml(
    packDir,
    `- insert:\n    - id: ${offendingId}\n      name: '${join(packDir, 'hostile.js')}'\n      config: {}\n`,
    'tampered-id-collision-no-pack-digest',
  )
  return { overlayPath, overlayYaml: readFileSync(overlayPath, 'utf8'), offendingId }
}

// ---------- 最小 tar 读取器（场景二的 digest 三阶段锚） ----------

export interface TarballEntry {
  /** 包内相对路径（posix 分隔，无前导 ./，npm pack 的 package/ 前缀保留）。 */
  readonly path: string
  readonly content: Buffer
}

const TAR_BLOCK = 512

function parseOctal(field: Buffer): number {
  const text = field.toString('latin1').replace(/\0.*$/s, '').trim()
  return text === '' ? 0 : Number.parseInt(text, 8)
}

/**
 * 手写最小 ustar+pax 读取器——read-only 镜像 apps/node/src/plugin/tar.ts
 * `unpackTarGz`（边界红线：本包不得 import apps/node，探针复制读取语义并互引；
 * 写侧 buildTarGz 产的 committed tarball 是纯 ustar，pax path 支持仅为对齐）。
 * 这里不做安装侧安全校验（路径/类型拒绝在 apps/node 有专测）：探针只读
 * repo 内 committed 文件，比对成员字节。
 */
export function readTarballEntries(archive: Buffer): TarballEntry[] {
  const tar = gunzipSync(archive)
  const entries: TarballEntry[] = []
  let paxPath: string | undefined
  let offset = 0
  for (;;) {
    if (offset + TAR_BLOCK > tar.length) break
    const header = tar.subarray(offset, offset + TAR_BLOCK)
    offset += TAR_BLOCK
    if (header.every((byte) => byte === 0)) break
    const typeflag = String.fromCharCode(header[156] ?? 0)
    const size = parseOctal(header.subarray(124, 136))
    const name = header.subarray(0, 100).toString('latin1').replace(/\0.*$/s, '')
    const content = tar.subarray(offset, offset + size)
    offset += Math.ceil(size / TAR_BLOCK) * TAR_BLOCK
    if (typeflag === 'x') {
      const text = content.toString('utf8')
      paxPath = /(?:^|\n)\d+ path=([^\n]+)/.exec(`\n${text}`)?.[1]
      continue
    }
    if (typeflag === 'g') continue
    if (typeflag !== '0' && typeflag !== '\0' && typeflag !== '7') continue
    entries.push({ path: paxPath ?? name, content: Buffer.from(content) })
    paxPath = undefined
  }
  return entries
}
