#!/usr/bin/env tsx
/**
 * P1-17 fixture 插件确定性重生成脚本（02 Task 17；plugins/ 数据树单一来源）。
 *
 * 从 `plugins/fixtures/whalepod-fixed-time/` 的未修改插件源码出发，用
 * apps/node 的规范化写入器 buildTarGz（uid/gid 0、mtime 0、按路径排序、
 * 固定 gzip 参数；npm 布局 package/ 前缀）产出确定性 tarball，再现算全部
 * digest 并写出/校验三个登记文件：
 *
 *   plugins/tarballs/whalepod-fixed-time-0.1.0.tgz   确定性 tar.gz
 *   plugins/locks/whalepod-fixed-time@0.1.0.lock.yaml 受审依赖闭包（空闭包）
 *   plugins/catalog/whalepod-fixed-time.json          review overlay manifest
 *   plugins/curated-pack.json                           预组装不可变 Pack 登记
 *
 * 何时跑：
 *   - 改了 plugins/fixtures/whalepod-fixed-time/ 下任何文件、protocol 的
 *     digest 算法或 apps/node 的 tar/lockfile 实现后，必须重跑默认模式，
 *     并把重生成的四个文件与源码改动放进同一个提交（digest 漂移 = 登记失效）。
 *   - `--check` 只验不写，退出码非零即漂移，适合接进 CI 门（接哪个门由
 *     主代理决定；本脚本不改 CI/package.json）。
 *
 * review.commit / review.at 是生成时的 provenance 快照（git rev-parse HEAD /
 * 生成时刻），不是可复算值：--check 只验其形状（40 位 hex / ISO 时间），
 * 不与当前 HEAD 比对——否则任何后续提交都会让登记自引用失效。需要刷新
 * 审核快照时显式重跑默认模式。
 *
 * 实现说明：本脚本属业务侧，不 import @deepseek-ai/*。tar/lockfile 算法从
 * apps/node 源码相对路径引入（tsx 直接跑 TS），protocol 的 manifest/entry/
 * digest 算法从 packages/protocol 源码引入；apps/node 与 fixture 测试里的
 * 对应实现走 `@whalepod/protocol` 构建产物（dist），src/dist 一旦漂移会被
 * apps/node/tests/plugin-fixture.spec.ts 的复算断言拦截。
 */
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { buildTarGz } from '../apps/node/src/plugin/tar.js'
import { digestLockfile, parseLockfile } from '../apps/node/src/plugin/lockfile.js'
import {
  PluginManifestSchema,
  type PluginManifest,
} from '../packages/protocol/src/plugin-manifest.js'
import { pluginCordisEntry } from '../packages/protocol/src/plugin-runtime-config.js'
import {
  digestPluginCordisEntry,
  digestPluginPack,
} from '../packages/protocol/src/plugin-pack-digest.js'

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url))
const FIXTURE_DIR = join(REPO_ROOT, 'plugins/fixtures/whalepod-fixed-time')
const TARBALL_PATH = join(REPO_ROOT, 'plugins/tarballs/whalepod-fixed-time-0.1.0.tgz')
const LOCK_PATH = join(REPO_ROOT, 'plugins/locks/whalepod-fixed-time@0.1.0.lock.yaml')
const CATALOG_PATH = join(REPO_ROOT, 'plugins/catalog/whalepod-fixed-time.json')
const PACK_PATH = join(REPO_ROOT, 'plugins/curated-pack.json')
const DSH_LOCK_PATH = join(REPO_ROOT, 'dsh.lock.json')

const PACKAGE_NAME = 'whalepod-fixed-time'
const PACKAGE_VERSION = '0.1.0'
const PACK_NAME = 'fixed-time'
const ENTRYPOINT = 'index.js'
const TARBALL_URL = `https://registry.npmjs.org/${PACKAGE_NAME}/-/${PACKAGE_NAME}-${PACKAGE_VERSION}.tgz`

// ---------- 现算 ----------

/** fixture 源码目录的全部普通文件（相对路径 + 字节），递归、排序交给 buildTarGz。 */
function readFixtureEntries(): Array<{ path: string; content: Buffer }> {
  const out: Array<{ path: string; content: Buffer }> = []
  const walk = (dir: string, prefix: string): void => {
    for (const name of readdirSync(dir).sort()) {
      const abs = join(dir, name)
      if (!statSync(abs).isFile()) continue
      out.push({ path: prefix === '' ? name : `${prefix}/${name}`, content: readFileSync(abs) })
    }
  }
  walk(FIXTURE_DIR, '')
  if (out.length === 0) throw new Error(`fixture source dir is empty: ${FIXTURE_DIR}`)
  return out
}

/** 用 apps/node 的规范化写入器重打包（npm 布局 package/ 根前缀，文件条目）。 */
function rebuildTarball(): Buffer {
  const entries = readFixtureEntries().map((entry) => ({
    path: `package/${entry.path}`,
    content: entry.content,
  }))
  return buildTarGz(entries)
}

/** sha256 SRI（catalog 制作口径，与 apps/node verifyIntegrity 兼容）。 */
function sriSha256(content: Buffer): string {
  return `sha256-${createHash('sha256').update(content).digest('base64')}`
}

/** dsh.lock.json 里 DSH 本体的精确版本 → manifest.dshCompatibility。 */
function readDshCompatibility(): string {
  const lock = JSON.parse(readFileSync(DSH_LOCK_PATH, 'utf8')) as {
    packages?: Record<string, { version?: string }>
  }
  const version = lock.packages?.['@deepseek-ai/dsh']?.version
  if (typeof version !== 'string' || version === '') {
    throw new Error(`cannot read @deepseek-ai/dsh version from ${DSH_LOCK_PATH}`)
  }
  return version
}

/** 生成时 HEAD（review provenance 快照）。 */
function gitHead(): string {
  return execFileSync('git', ['-C', REPO_ROOT, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim()
}

/** 受审依赖闭包：fixture 对 dsh-tools 只声明 peerDependency（宿主提供），闭包为空。 */
function buildLockYaml(): string {
  return [
    '# Curated dependency closure lockfile (02 Task 17 Step 4).',
    '# Generated by scripts/build-fixture-plugin.mts — do not edit by hand.',
    '# Regenerate: pnpm exec tsx scripts/build-fixture-plugin.mts',
    '# @deepseek-ai/dsh-tools is a peerDependency provided by the host DSH',
    '# distribution, so the installable closure is empty.',
    'schemaVersion: 1',
    'package:',
    `  name: ${PACKAGE_NAME}`,
    `  version: ${PACKAGE_VERSION}`,
    'dependencies: []',
    '',
  ].join('\n')
}

interface ComputedPack {
  manifest: PluginManifest
  lockYaml: string
  lockDigest: string
  packEntry: {
    name: string
    version: string
    integrity: string
    dependencyLockDigest: string
    entrypoint: string
    configDigest: string
  }
  pack: { schemaVersion: 1; name: string; packages: unknown[]; packDigest: string }
}

/** 由 tarball 字节现算 manifest + lockfile 文本 + Pack 登记（review 用传入快照）。 */
function compute(review: PluginManifest['review']): ComputedPack {
  const tarball = rebuildTarball()
  const integrity = sriSha256(tarball)
  const lockYaml = buildLockYaml()
  // 落盘前先走 apps/node 的真实解析 + digest 算法，杜绝手写 yaml 与实现漂移。
  const lockDigest = digestLockfile(parseLockfile(lockYaml))
  const manifest = PluginManifestSchema.parse({
    schemaVersion: 1,
    name: PACKAGE_NAME,
    version: PACKAGE_VERSION,
    tarballUrl: TARBALL_URL,
    integrity,
    dependencyLockDigest: lockDigest,
    dshCompatibility: readDshCompatibility(),
    entrypoint: ENTRYPOINT,
    capabilities: [],
    capabilityClass: 'declared',
    license: 'Apache-2.0',
    review,
  })
  const configDigest = digestPluginCordisEntry(pluginCordisEntry(manifest))
  const packEntry = {
    name: manifest.name,
    version: manifest.version,
    integrity: manifest.integrity,
    dependencyLockDigest: manifest.dependencyLockDigest,
    entrypoint: manifest.entrypoint,
    configDigest,
  }
  const pack = {
    schemaVersion: 1 as const,
    name: PACK_NAME,
    packages: [packEntry],
    packDigest: digestPluginPack({ schemaVersion: 1, packages: [packEntry] }),
  }
  return { manifest, lockYaml, lockDigest, packEntry, pack }
}

// ---------- 写出 / 校验 ----------

function stableStringify(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value)
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`
  const entries = Object.entries(value as Record<string, unknown>).sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  )
  return `{${entries.map(([k, v]) => `${JSON.stringify(k)}:${stableStringify(v)}`).join(',')}}`
}

function writeJson(path: string, value: unknown): void {
  mkdirSync(join(path, '..'), { recursive: true })
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`)
}

function runDefault(): number {
  const review = { status: 'reviewed' as const, commit: gitHead(), at: new Date().toISOString() }
  const computed = compute(review)
  mkdirSync(join(TARBALL_PATH, '..'), { recursive: true })
  writeFileSync(TARBALL_PATH, rebuildTarball())
  writeJson(CATALOG_PATH, computed.manifest)
  mkdirSync(join(LOCK_PATH, '..'), { recursive: true })
  writeFileSync(LOCK_PATH, computed.lockYaml)
  writeJson(PACK_PATH, computed.pack)
  console.log(`tarball                ${TARBALL_PATH}`)
  console.log(`  integrity (sha256)   ${computed.manifest.integrity}`)
  console.log(`lock                   ${LOCK_PATH}`)
  console.log(`  dependencyLockDigest ${computed.lockDigest}`)
  console.log(`catalog                ${CATALOG_PATH}`)
  console.log(`  review.commit        ${review.commit}`)
  console.log(`  configDigest         ${computed.packEntry.configDigest}`)
  console.log(`pack                   ${PACK_PATH}`)
  console.log(`  packDigest           ${computed.pack.packDigest}`)
  return 0
}

function runCheck(): number {
  const failures: string[] = []
  const expectEqual = (what: string, actual: unknown, expected: unknown): void => {
    if (stableStringify(actual) !== stableStringify(expected)) {
      failures.push(
        `${what} drifted:\n  committed: ${stableStringify(actual)}\n  recomputed: ${stableStringify(expected)}`,
      )
    }
  }

  // 1. 确定性重打包 == 已提交 tarball 字节。
  const recomputed = compute({
    status: 'reviewed',
    commit: '0'.repeat(40),
    at: new Date(0).toISOString(),
  })
  if (!existsSync(TARBALL_PATH)) {
    failures.push(`tarball missing: ${TARBALL_PATH}`)
  } else {
    const committed = readFileSync(TARBALL_PATH)
    if (!committed.equals(rebuildTarball())) {
      failures.push(`tarball bytes drifted: ${TARBALL_PATH} != deterministic rebuild from fixtures`)
    }
  }

  // 2. catalog manifest：schema 合法 + 除 review 快照外全部字段与现算一致。
  let review: PluginManifest['review'] | undefined
  if (!existsSync(CATALOG_PATH)) {
    failures.push(`catalog missing: ${CATALOG_PATH}`)
  } else {
    const parsedManifest = PluginManifestSchema.safeParse(
      JSON.parse(readFileSync(CATALOG_PATH, 'utf8')),
    )
    if (!parsedManifest.success) {
      failures.push(`catalog rejected by PluginManifestSchema: ${parsedManifest.error.message}`)
    } else {
      review = parsedManifest.data.review
      if (review.status !== 'reviewed') failures.push(`catalog review.status must be 'reviewed'`)
      const expected = compute(review).manifest
      expectEqual('catalog manifest', parsedManifest.data, expected)
    }
  }

  // 3. lock yaml：parseLockfile 可解析、root 匹配、digest 与现算一致。
  if (!existsSync(LOCK_PATH)) {
    failures.push(`lock missing: ${LOCK_PATH}`)
  } else {
    try {
      const lock = parseLockfile(readFileSync(LOCK_PATH, 'utf8'))
      expectEqual('lock package', lock.package, { name: PACKAGE_NAME, version: PACKAGE_VERSION })
      expectEqual('lock digest', digestLockfile(lock), recomputed.lockDigest)
    } catch (error) {
      failures.push(`lock unparseable: ${String(error)}`)
    }
  }

  // 4. curated-pack：整体（含 configDigest/packDigest）与现算一致。
  //    pack 字段不依赖 review 快照，直接与占位快照的现算值比对即可。
  if (!existsSync(PACK_PATH)) {
    failures.push(`pack missing: ${PACK_PATH}`)
  } else {
    const committedPack = JSON.parse(readFileSync(PACK_PATH, 'utf8'))
    expectEqual('curated pack', committedPack, recomputed.pack)
  }

  if (failures.length > 0) {
    console.error(`build-fixture-plugin --check: ${failures.length} drift(s)`)
    for (const failure of failures) console.error(`- ${failure}`)
    console.error('rerun: pnpm exec tsx scripts/build-fixture-plugin.mts')
    return 1
  }
  console.log('build-fixture-plugin --check: OK')
  console.log(`  integrity (sha256)   ${recomputed.manifest.integrity}`)
  console.log(`  dependencyLockDigest ${recomputed.lockDigest}`)
  console.log(`  packDigest           ${recomputed.pack.packDigest}`)
  return 0
}

const checkOnly = process.argv.slice(2).includes('--check')
process.exitCode = checkOnly ? runCheck() : runDefault()
